-----------------   Create Table ( Oracle ) --------------

alter session set deferred_segment_creation=false;


DROP TABLE WORKITEM;
DROP TABLE SUBSYS;
DROP TABLE MEMBER;
DROP TABLE PLAN;


DROP SEQUENCE workitem_seq;
DROP SEQUENCE plan_seq;
DROP SEQUENCE subsys_seq;
DROP SEQUENCE member_seq;

CREATE TABLE MEMBER (
  PK_MEMBER            NUMBER(7,0)  NOT NULL,
  MEM_NAME          VARCHAR2(20) NOT NULL,
  MEM_PASSWORD      VARCHAR2(20) NOT NULL,
  MEM_EMAIL         VARCHAR2(30) NOT NULL,
  MEM_PHOTO    		BLOB, 
  CONSTRAINT MEMBER_PRIMARY_KEY PRIMARY KEY (PK_MEMBER));

CREATE SEQUENCE member_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

insert into Member(PK_MEMBER, MEM_NAME, MEM_PASSWORD, MEM_EMAIL) 
values(member_seq.nextVal,'Test','123456','xxx@xxx.com.tw');

CREATE TABLE SUBSYS(
  PK_SUBSYS				NUMBER(7,0) NOT NULL,
  SUBSYS_ENG_NAME       VARCHAR2(30) NOT NULL,
  SUBSYS_TW_NAME     	VARCHAR2(30) NOT NULL,
  CONSTRAINT SUBSYS_PRIMARY_KEY PRIMARY KEY (PK_SUBSYS));

CREATE SEQUENCE subsys_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

insert into SUBSYS(PK_SUBSYS,SUBSYS_ENG_NAME,SUBSYS_TW_NAME)
values(subsys_seq.nextVal, ' ', '待辦事項');


CREATE TABLE PLAN (
  PK_PLAN    	    NUMBER(7,0)   NOT NULL,
  PLAN_YEAR			NUMBER(7,0)	  NOT NULL,
  PLAN_START_DATE	DATE		  NOT NULL,
  PLAN_END_DATE		DATE		  NOT NULL,
  PLAN_NAME			VARCHAR2(40)  NOT NULL,
  CONSTRAINT PLAN_PRIMARY_KEY PRIMARY KEY (PK_PLAN ));
  
CREATE SEQUENCE plan_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE TABLE WORKITEM (
  PK_WORKITEM    	    NUMBER(7,0)   NOT NULL,
  WORKITEM_NAME  	    VARCHAR2(300) NOT NULL,
  WORKITEM_CONTENT      VARCHAR2(300) NOT NULL,
  WORKITEM_HOUR		    NUMBER(7,2)   NOT NULL,
  WORKITEM_DATE			DATE		  NOT NULL,
  WORKITEM_SUBSYS		VARCHAR2(30)  NOT NULL,
  WORKITEM_MEMBER		VARCHAR2(30)  NOT NULL,
  FK_PLAN				NUMBER(7,0)   NOT NULL,
  CONSTRAINT WORKITEM_FOREIGN_KEY1 FOREIGN KEY(FK_PLAN) REFERENCES PLAN (PK_PLAN),
  CONSTRAINT WORKITEM_PRIMARY_KEY PRIMARY KEY (PK_WORKITEM));
  
CREATE SEQUENCE workitem_seq
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


commit;


-- MY SQL --
-----------------   Create Table --------------

alter session set deferred_segment_creation=false;

use [sp2021]

DROP TABLE sp2021.WORKITEM;
DROP TABLE sp2021.SUBSYS;
DROP TABLE sp2021.MEMBER;
DROP TABLE sp2021.PLAN;


DROP SEQUENCE sp2021.workitem_seq;
DROP SEQUENCE sp2021.plan_seq;
DROP SEQUENCE sp2021.subsys_seq;
DROP SEQUENCE sp2021.member_seq;

CREATE TABLE sp2021.MEMBER (
  PK_MEMBER            int(7)  NOT null AUTO_INCREMENT,
  MEM_NAME          nvarchar(20) NOT NULL,
  MEM_PASSWORD      nvarchar(20) NOT NULL,
  MEM_EMAIL         nvarchar(30) NOT NULL,
  MEM_PHOTO    		BLOB, 
  CONSTRAINT MEMBER_PRIMARY_KEY PRIMARY KEY (PK_MEMBER));


insert into sp2021.Member(MEM_NAME, MEM_PASSWORD, MEM_EMAIL) 
values('Test','123456','xxx@xxx.com.tw');

CREATE TABLE sp2021.SUBSYS(
  PK_SUBSYS				int(7) NOT null AUTO_INCREMENT,
  SUBSYS_ENG_NAME       nvarchar(30) NOT NULL,
  SUBSYS_TW_NAME     	nvarchar(30) NOT NULL,
  CONSTRAINT SUBSYS_PRIMARY_KEY PRIMARY KEY (PK_SUBSYS));


insert into sp2021.SUBSYS(SUBSYS_ENG_NAME,SUBSYS_TW_NAME)
values(' ', '待辦事項');


CREATE TABLE sp2021.PLAN (
  PK_PLAN    	    int(7)   NOT null AUTO_INCREMENT,
  PLAN_YEAR			int(7)	  NOT NULL,
  PLAN_START_DATE	DATE		  NOT NULL,
  PLAN_END_DATE		DATE		  NOT NULL,
  PLAN_NAME			nvarchar(40)  NOT NULL,
  CONSTRAINT PLAN_PRIMARY_KEY PRIMARY KEY (PK_PLAN ));
  

CREATE TABLE sp2021.WORKITEM (
  PK_WORKITEM    	    int(7)   NOT null AUTO_INCREMENT,
  WORKITEM_NAME  	    nvarchar(300) NOT NULL,
  WORKITEM_CONTENT      nvarchar(300) NOT NULL,
  WORKITEM_HOUR		    int(7)   NOT NULL,
  WORKITEM_DATE			DATE		  NOT NULL,
  WORKITEM_SUBSYS		nvarchar(30)  NOT NULL,
  WORKITEM_MEMBER		nvarchar(30)  NOT NULL,
  FK_PLAN				int(7)   NOT NULL,
  constraint WORKITEM_FOREIGN_KEY1 FOREIGN KEY(FK_PLAN) REFERENCES PLAN (PK_PLAN),
  CONSTRAINT WORKITEM_PRIMARY_KEY PRIMARY KEY (PK_WORKITEM));
  

commit;